### PR TITLE
Updated indicator_8-6-1.csv

### PR DESCRIPTION
**Pull request by raichoudhary-r**
This pull request has been automatically generated by prose.io.

### CODE REVIEW

**Comment by JenPark9** [comment]
Hi Ronjoy,
I am accepting this pull request. Please take a look and let me know if all is in order. Thank you, Jennifer

**Comment by raichoudhary-r** [comment]
Hi Jennifer,

Everything looks to be in order.

I had a question about one of the metadata fields: For “Date of last Update of This Page”, does that refer to when the NRP page was last updated, or when the page the source data are available from was last updated?

Thanks,

Ronjoy

**Comment by JenPark9** [comment]
The former. Thanks!
Does this indicator have a graph associated w it yet? If not, I will address tomorrow.
Best, Jen

Sent from my iPhone

On Jan 3, 2017, at 6:39 PM, raichoudhary-r <notifications@github.com<mailto:notifications@github.com>> wrote:
Hi Jennifer,

Everything looks to be in order.

I had a question about one of the metadata fields: For "Date of last Update of This Page", does that refer to when the NRP page was last updated, or when the page the source data are available from was last updated?

Thanks,

Ronjoy

**Comment by raichoudhary-r** [comment]
In that case, I should be inputting the current date every time I update either the data or metadata tabs – is that correct?

This indicator already has a graph associated with it.

Thanks!

Ronjoy

**Comment by JenPark9** [comment]
Yep, but when I can, I've tried to fill that in for you on your indicators. No prob.
Thanks!

Sent from my iPhone

On Jan 3, 2017, at 6:57 PM, raichoudhary-r <notifications@github.com<mailto:notifications@github.com>> wrote:

In that case, I should be inputting the current date every time I update either the data or metadata tabs - is that correct?

This indicator already has a graph associated with it.

Thanks!

Ronjoy

**Pull request merged**
