### PR TITLE
Updated indicator 3.9.3 with 2014 data

### PR DESCRIPTION
**Pull request by ambranu**
This pull request has been automatically generated by prose.io.

### CODE REVIEW

**Comment by JenPark9** [comment]
Accepting!

**Comment by ambranu** [comment]
Thanks Jen!  I’m waiting on the metadata now.  The person who sent me the data just sent me the estimates so I have asked her to also supply the metadata.  I will input that as soon as I receive it.  I think this concludes the estimates that I was responsible for entering data but I’ll double check.

Thanks,
Amy

**Comment by JenPark9** [comment]
Righto—thank you!

**Comment by JenPark9** [comment]
Thanks, Amy!
Could you double check on the indicator below? Not sure if Jennifer assigned it to you or not, but maybe in your purview?

16.9.1 Proportion of children under 5 years of age whose births have been registered with a civil authority, by age

Jennifer Madans (NCHS)

jhm4@cdc.gov

September

Assigned

**Comment by ambranu** [comment]
Hi Jen,
Jennifer did not assign this one to us.  I’m not sure why but it sort of sounds like one of those indicators that does not apply to the US data like it might for other countries?  We estimate that we register at least 99% of all births in the US annually and that percentage does not fluctuate over time.  I could ask her about it?

Amy

**Comment by JenPark9** [comment]
Yes, please. Even if at least 99% are registered, then we would want to provide data points to facilitate comparisons globally. Thank you!

**Comment by ambranu** [comment]
Okay, I’ll touch base with Jennifer!

**Comment by ambranu** [comment]
Hi again Jen,
I checked with Jennifer and she did say to go ahead and input for this indicator.  I wanted to let you know what I was planning to do though, since this indicator isn’t completely applicable to the US in terms of its definition.  I was just going to essentially put down 100% basing this only on the number of US births that are registered for each year.  We can’t know out of all of the children currently living in the US who are under 5 how many were registered by a civil authority, accounting for immigration, so the easiest thing to do is just list the percentage of children born in the US who are registered which will be approximately 100%.  Is that okay?  I’ll make sure the metadata reflects this.

Thanks,
Amy

**Comment by JenPark9** [comment]
Yes, thank you, Amy!

**Pull request merged**
