### PR TITLE
Brianna test as Travis was having difficulty

### PR DESCRIPTION
**Pull request by briannabesch**
This pull request has been automatically generated by prose.io.

### CODE REVIEW

**Comment by JenPark9** [comment]
Brianna, Travis sent many update requests. They will not appear on the site until I approve them, so he may have thought that I did not receive his request (I was in a meeting). Could you check in with him now and make sure that all looks as it should? Thanks!

**Comment by briannabesch** [comment]
Hi Jen,

For some reason once Travis saved the  changes and re-loaded the site he could no longer see them – they should be good to go, just duplicated.

Brianna Besch
Office of Global Affairs and Policy
U.S. Environmental Protection Agency
+1-202-564-4146
besch.brianna@epa.gov<mailto:besch.brianna@epa.gov>

**Comment by briannabesch** [comment]
Hi Brianna,
Yes, when the updates are entered and saved, they do not appear on the site until I have approved them. If he went back into the edit mode, he would see them, though. In any case, please confirm that the values are now correct and up to date.
Thank you!
Jennifer

From: Besch, Brianna [mailto:besch.brianna@epa.gov]
Sent: Wednesday, November 1, 2017 1:53 PM
To: GSA/sdg-indicators <reply@reply.github.com>; GSA/sdg-indicators <sdg-indicators@noreply.github.com>
Cc: Author <author@noreply.github.com>; Park, Jennifer E. EOP/OMB <Jennifer_E_Park@omb.eop.gov>
Subject: RE: [GSA/sdg-indicators] Brianna test as Travis was having difficulty (#778)

Hi Jen,

For some reason once Travis saved the  changes and re-loaded the site he could no longer see them – they should be good to go, just duplicated.

Brianna Besch
Office of Global Affairs and Policy
U.S. Environmental Protection Agency
+1-202-564-4146
besch.brianna@epa.gov<mailto:besch.brianna@epa.gov>

**Comment by briannabesch** [comment]
Hi Jen,

Travis is going through now and will confirm with you shortly!

Brianna Besch
Office of Global Affairs and Policy
U.S. Environmental Protection Agency
+1-202-564-4146
besch.brianna@epa.gov<mailto:besch.brianna@epa.gov>

From: Park, Jennifer E. EOP/OMB [mailto:Jennifer_E_Park@omb.eop.gov]
Sent: Wednesday, November 01, 2017 1:56 PM
To: Besch, Brianna <besch.brianna@epa.gov>; GSA/sdg-indicators <reply@reply.github.com>; GSA/sdg-indicators <sdg-indicators@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [GSA/sdg-indicators] Brianna test as Travis was having difficulty (#778)

Hi Brianna,
Yes, when the updates are entered and saved, they do not appear on the site until I have approved them. If he went back into the edit mode, he would see them, though. In any case, please confirm that the values are now correct and up to date.
Thank you!
Jennifer

From: Besch, Brianna [mailto:besch.brianna@epa.gov]
Sent: Wednesday, November 1, 2017 1:53 PM
To: GSA/sdg-indicators <reply@reply.github.com<mailto:reply@reply.github.com>>; GSA/sdg-indicators <sdg-indicators@noreply.github.com<mailto:sdg-indicators@noreply.github.com>>
Cc: Author <author@noreply.github.com<mailto:author@noreply.github.com>>; Park, Jennifer E. EOP/OMB <Jennifer_E_Park@omb.eop.gov<mailto:Jennifer_E_Park@omb.eop.gov>>
Subject: RE: [GSA/sdg-indicators] Brianna test as Travis was having difficulty (#778)

Hi Jen,

For some reason once Travis saved the  changes and re-loaded the site he could no longer see them – they should be good to go, just duplicated.

Brianna Besch
Office of Global Affairs and Policy
U.S. Environmental Protection Agency
+1-202-564-4146
besch.brianna@epa.gov<mailto:besch.brianna@epa.gov>

**Pull request closed without merging**
