### PR TITLE
added number of commercial banking establishments for year 2002

### PR DESCRIPTION
**Pull request by jacob2479**
This pull request has been automatically generated by prose.io.

### CODE REVIEW

**Comment by JenPark9** [comment]
Thank you! Please confirm by return email that the data appear as intended. Also, please be sure to update the metadata page to ensure that your contact information is correct, and that the date of update is provided in YYYY-MM-DD format. Best, Jennifer

**Comment by jacob2479** [comment]
The data appear as intended.


I updated my profile, which I assume is the metadata you reference, if not please advise on how/where to update.


I could not locate the date field for the update I made.


Thank you,

Faye




Faye Jacobs

Section Chief

Finance and Real Estate Services Branch

Economy Wide Statistics Division

U.S. Census Bureau


Office 301.763.7177

faye.ann.jacobs@census.gov


census.gov<http://www.census.gov/>

Connect with us on Social Media<http://www.census.gov/about/contact-us/social_media.html>



________________________________

**Comment by JenPark9** [comment]
Hi Faye,
You will also want to update the metadata page.  Here is a snip. You would use the same procedure to submit changes.
Thanks!
[cid:image001.jpg@01D33D16.203C8B90]

**Comment by jacob2479** [comment]
Thank you for your assistance.


I was able to successfully update the metadata.


Thanks again,

Faye




Faye Jacobs

Section Chief

Finance and Real Estate Services Branch

Economy Wide Statistics Division

U.S. Census Bureau


Office 301.763.7177

faye.ann.jacobs@census.gov


census.gov<http://www.census.gov/>

Connect with us on Social Media<http://www.census.gov/about/contact-us/social_media.html>



________________________________

**Comment by JenPark9** [comment]
Thanks, Faye. Please confirm that you submitted the change. I have not received the pull request just yet (maybe making its way through the ether…).
Best, Jen

**Pull request merged**
