### PR TITLE
Updated metadata for US adolescent teen births

### PR DESCRIPTION
**Pull request by ambranu**
This pull request has been automatically generated by prose.io.

### CODE REVIEW

**Comment by JenPark9** [comment]
Hi Amy,
Just letting you know that I received these and will review/accept first thing tomorrow. Thanks!

Sent from my iPhone

On Sep 20, 2016, at 5:15 PM, ambranu <notifications@github.com<mailto:notifications@github.com>> wrote:


This pull request has been automatically generated by prose.io<http://prose.io>.

________________________________
You can view, comment on, or merge this pull request online at:

  >https://github.com/GSA/sdg-indicators/pull/131<

Commit Summary

  *   Updated metadata for US adolescent teen births

File Changes

  *   M _indicators/3-7-2.md<>https://github.com/GSA/sdg-indicators/pull/131/files<#diff-0> (138)

Patch Links:

  *   >https://github.com/GSA/sdg-indicators/pull/131.patch<
  *   >https://github.com/GSA/sdg-indicators/pull/131.diff<

**Comment by ambranu** [comment]
Great thanks Jen!  Also, I think I’m done with all of the indicators for which I have been given data at this point.  I believe there will be some additional mortality indicators but I have not been given the data for these.  I’m going on vacation for 2 weeks starting this Friday.  I’ll touch base with Jennifer and let her know the status of what I have entered and that I’ll be out for a couple of weeks but you probably won’t hear more from me via this platform for a few weeks ☺

**Comment by JenPark9** [comment]
Righto. Thanks, Amy!

Sent from my iPhone

On Sep 20, 2016, at 5:44 PM, ambranu <notifications@github.com<mailto:notifications@github.com>> wrote:

Great thanks Jen! Also, I think I'm done with all of the indicators for which I have been given data at this point. I believe there will be some additional mortality indicators but I have not been given the data for these. I'm going on vacation for 2 weeks starting this Friday. I'll touch base with Jennifer and let her know the status of what I have entered and that I'll be out for a couple of weeks but you probably won't hear more from me via this platform for a few weeks :)

**Comment by JenPark9** [comment]
Accepting--thank you, Amy!

**Pull request merged**
