### PR TITLE
Realized that the occupation codes prior to 2010 are not comparable to the 2010 and after codes. Thus removed the 2005-2009 data that had previously submitted.

### PR DESCRIPTION
**Pull request by smith165GITHUB**
This pull request has been automatically generated by prose.io.

### CODE REVIEW

**Comment by JenPark9** [comment]
Hi Amy,
I will delete these rows for you. Can you confirm that you could not bridge the occupation codes using SOC guidance? If you need help with that, I can put you in touch with folks. Please let me know.
Jen

**Comment by smith165GITHUB** [comment]
Hi Jen,


Yes I spoke with Lynda Laughlin who is Chief of the Occupation and Industry branch here and he indicated it would take a special tabulation to bridge the codes since prior to 2010 occupations were put into different categories.


Amy

________________________________

**Comment by JenPark9** [comment]
Ok, may we request the special tabulation?

**Comment by smith165GITHUB** [comment]
Let me ask Lynda and I will get back to you.


Amy


________________________________

**Comment by JenPark9** [comment]
Thank you!!

**Comment by smith165GITHUB** [comment]
Hi Jen,


I spoke to Lynda and she indicated that the data for years 2005-2009 can be calculated although it will require some special tabulations since the occupation category is not directly comparable between the two periods. To do this, extra time might be needed which could bump the delivery of these data past this Friday (10/13). Will this cause a problem in your schedule?


Also, Lynda and I have agreed that it would be best if her area becomes the contact for this indicator instead of me. When the data are downloaded in Github the metadata will be updated with a new contact person. When that's done I can also pass the new contact along to you and Kali.


Thanks, Amy


________________________________

**Comment by JenPark9** [comment]
Thank you, Amy. This is fine. Very much appreciate your (and Lynda’s) flexibility.
Best, Jennifer

**Pull request closed without merging**
