### PR TITLE
Populating indicator 7.2.1, data from table 1.3 from Monthly Energy Review,  July 2016

### PR DESCRIPTION
**Pull request by maggiewoodward**
This pull request has been automatically generated by prose.io.

### CODE REVIEW

**Comment by maggiewoodward** [comment]
Hi Jennifer-- Sorry, no, not quite yet. What's in there currently are my entries from the training/practice session in early August. I'm playing catch up from vacation, but I'll have it done by tomorrow afternoon.
Thanks,
Maggie

**Comment by maggiewoodward** [comment]
Actually-- I can't even see the data/metadata I put in that day anymore!

**Comment by JenPark9** [comment]
Checking

**Comment by JenPark9** [comment]
!  Phil, can you take a look at this? Do I need to merge her pull requests so that she can see her earlier entries? Thanks.

**Comment by JenPark9** [comment]
We will get back to you soon. I think I just need to merge a pull request.

**Comment by JenPark9** [comment]
Maggie,
You should be able to see the inputs you provided earlier to indicator 7.2.1. Please go ahead and make any further edits or additions as described in the training guide.
Thanks, Jennifer

**Pull request merged**
