### PR TITLE
2003 data explanation removed.

### PR DESCRIPTION
**Pull request by nicolenorris**
This pull request has been automatically generated by prose.io.

### CODE REVIEW

**Comment by JenPark9** [comment]
Thank you, Nicole. Let me know if you are confirming that your inputs are now complete.
Best, Jennifer

**Comment by nicolenorris** [comment]
Jennifer,

The data table is complete for NASS. I have updated the metadata table to ensure all references to 2003 are removed.
Nicole

**Comment by JenPark9** [comment]
Thank you very much, Nicole. We will be adding a graph for 6.5.1. today.
Please send a courtesy email to your expert group co-chairs letting them know you have completed inputs for 6.5.1. An example email is below, if helpful.

CC:  Jennifer Park; Mark Miller
Dear
Dan Balzer (BalzerDK@state.gov);

Wilson Sumner (SumnerW@state.gov<mailto:SumnerW@state.gov>)

I wanted to let you know that the statistics and metadata for indicators 7.2.1 and 7.3.1 have been populated on the national reporting platform. You can view the site at: https://gsa.github.io/sdg-indicators/.
If you have any questions, please let me know.
Sincerely,

Best, Jennifer

**Comment by JenPark9** [comment]
Also, Nicole, will you be able to provide input to 15.1.1.? Is that still under development, or…? Just checking.
Thank you, Jennifer

**Comment by nicolenorris** [comment]
Jennifer,

We are still working on input for 15.1.1. hopefully we will have something within the next week or so.

Nicole Norris
Agricultural Statistician
International Programs Office
USDA, National Agricultural Statistics Service
Office Phone:  (202) 720-6016
Cell Phone: (202) 619-9279

**Comment by JenPark9** [comment]
Thank you kindly, Nicole.
Best, Jennifer

**Pull request merged**
