### PR TITLE
Update 11-1-1.md

### PR DESCRIPTION
**Pull request by Davanden**
This pull request has been automatically generated by prose.io.

### CODE REVIEW

**Comment by JenPark9** [comment]
Thank you! Please confirm that data are not available for the period 2000-2006. If they are available, please add those as well. Last, please make sure to update the metadata with the date of update as 2017-10-10 (n that format).

**Comment by Davanden** [comment]
Jen,

AHS data are collected in odd-numbered years.  I can update the table for 2001, 2003, and 2005.

--Dav
david.a.vandenbroucke@hud.gov

**Comment by JenPark9** [comment]
Thank you, Dav!

**Comment by Davanden** [comment]
Okay, it’s done.

--Dav
david.a.vandenbroucke@hud.gov

**Pull request merged**
