### PR TITLE
Update 9-5-1.md

### PR DESCRIPTION
**Pull request by mboroush**
This pull request has been automatically generated by prose.io.

### CODE REVIEW

**Comment by JenPark9** [comment]
Thank you, Mark. If you could use the format of 2017-10-19 for your date of update, that will help us with some programming on our end. Best, Jen

**Comment by mboroush** [comment]
I have the data for 2000 to 2006. (Actually, the series goes back to 1953).  But I have no idea how to access a load sheet that goes back that far.  I’ve not found GitHub user-friendly.  Hard enough to find what I submitted last year, which I then simply updated.

So, please lead me know how I access a data entry tableau that allows the earlier year entry, and I will do so.


Mark Boroush
Senior Analyst
National Science Foundation, National Center for Science and Engineering Statistics
2415 Eisenhower Avenune, Room W14152
Alexandria, Virginia 22314
phone: 703.292.8726
email: mboroush@nsf.gov<mailto:mboroush@nsf.gov>

National Center for Science and Engineering Statistics
www.nsf.gov/statistics/<http://www.nsf.gov/statistics/>

**Comment by JenPark9** [comment]
Sure; it works like excel. You would right click on a row and then select insert row (above or below).
I am glad to do it for you if that helps.

**Comment by JenPark9** [comment]
I am going to add the rows for you; back in a sec.

**Comment by mboroush** [comment]
I can do it, if it is no more than that.


Mark Boroush
Senior Analyst
National Science Foundation, National Center for Science and Engineering Statistics
2415 Eisenhower Avenune, Room W14152
Alexandria, Virginia 22314
phone: 703.292.8726
email: mboroush@nsf.gov<mailto:mboroush@nsf.gov>

National Center for Science and Engineering Statistics
www.nsf.gov/statistics/<http://www.nsf.gov/statistics/>

**Comment by JenPark9** [comment]
The rows should be up in a minute for you.

**Comment by mboroush** [comment]
OK.  Thanks.  I’ll try again.  And I note your request about the date format.

Mark Boroush
Senior Analyst
National Science Foundation, National Center for Science and Engineering Statistics
2415 Eisenhower Avenune, Room W14152
Alexandria, Virginia 22314
phone: 703.292.8726
email: mboroush@nsf.gov<mailto:mboroush@nsf.gov>

National Center for Science and Engineering Statistics
www.nsf.gov/statistics/<http://www.nsf.gov/statistics/>

**Pull request merged**
