### PR TITLE
Updated indicator_11-6-2.csv

### PR DESCRIPTION
**Pull request by dmintzepa**
This pull request has been automatically generated by prose.io.

### CODE REVIEW

**Comment by JenPark9** [comment]
Hello!
Just sending you a quick note that I received your pull requests and will review them tomorrow. Stay tuned!
Thank you,
Jen

Sent from my iPhone

On Sep 14, 2016, at 2:12 PM, dmintzepa <notifications@github.com<mailto:notifications@github.com>> wrote:


This pull request has been automatically generated by prose.io<http://prose.io>.

________________________________
You can view, comment on, or merge this pull request online at:

  >https://github.com/GSA/sdg-indicators/pull/112<

Commit Summary

  *   Updated indicator_11-6-2.csv

File Changes

  *   M data/indicator_11-6-2.csv<>https://github.com/GSA/sdg-indicators/pull/112/files<#diff-0> (20)

Patch Links:

  *   >https://github.com/GSA/sdg-indicators/pull/112.patch<
  *   >https://github.com/GSA/sdg-indicators/pull/112.diff<

-

**Comment by JenPark9** [comment]
Hi,
Please check your data and metadata pages to confirm that your inputs were received correctly. Please let me know if further edits are needed (you can use the usual procedure) or if you are finished reporting on this indicator.
Thank you, Jen

**Comment by dmintzepa** [comment]
Jen,

Everything looks good for this indicator.  Thanks!

-David

David Mintz | Senior Statistician | Air Quality Analysis Group – Mail Code C304-04 | Office of Air Quality Planning & Standards | U.S. Environmental Protection Agency | Research Triangle Park, NC 27711 | 919-541-5224

**Comment by JenPark9** [comment]
Great—thanks so much!

**Pull request closed without merging**
