### PR TITLE
2007-2014 poverty numbers

### PR DESCRIPTION
**Pull request by bglassman15910**
This pull request has been automatically generated by prose.io.

### CODE REVIEW

**Comment by JenPark9** [comment]
Hi there,
Please confirm that you are still working on this request (for example, adding metadata). 
Thank you, Jennifer

**Comment by bglassman15910** [comment]
I have added some metadata but I am done with the request now


Brian Glassman

Economist

Poverty Statistics Branch

Social, Economic and Housing Statistics Division

US Census Bureau

301-763-2463


________________________________

**Comment by JenPark9** [comment]
Hi Brian,
I am accepting this pull request--thank you. It will be visable from the website now. Please confirm that you have notified your expert group co-chairs of the populated content. If any updates need to be made, you may edit using the usual procedure.
Best, Jennifer

**Comment by JenPark9** [comment]
Brian,
Thanks for this. I think there are a few lines in the metadata page that still need your input, including your contact information. Can you take a look? (Perhaps I misunderstood that you were done inputting the metadata; apologies for that.)
Thank you, Jennifer

**Pull request merged**
