### PR TITLE
Updated indicator_9-5-1.csv

### PR DESCRIPTION
**Pull request by mboroush**
This pull request has been automatically generated by prose.io.

### CODE REVIEW

**Comment by JenPark9** [comment]
Hi there,
I'm accepting these input. Thank you! Please let me know when you have completed any updates to the metadata for this indicator as well.
Best, Jen

**Comment by mboroush** [comment]
I tried to deal with the metadata, but found GitHub a bit hard to move around in.  a) I couldn’t get to the metadata entry location after putting in the time series, without first fully signing out of the website and then back in.  Something didn’t work here as the training manual seemed to imply.  And b) I found numerous metadata entry requests, not all of which were clear regarding what info was being sought.  Do you have guidelines on this?

Mark Boroush
Senior Analyst
National Science Foundation, National Center for Science and Engineering Statistics
4201 Wilson Boulevard, Room 965.47
Arlington, Virginia 22230
phone: 703.292.8726
email: mboroush@nsf.gov

National Center for Science and Engineering Statistics
www.nsf.gov/statistics/<http://www.nsf.gov/statistics/>

**Comment by JenPark9** [comment]
Thank you, Mark. I am ccing Francisco at his NSF email address; maybe he can advise?
RE data entry, if you are still having difficulty, please let us know and we will assist.

**Comment by mboroush** [comment]
No problem in getting back into the SDG website, including access to editing the Metadata.  Just seemed a bit weird that I had to first sign out and then re-sign in to get there.

Bigger issue is the prompting seems to be for many metadata entries.  Not clear to me if all of these are of OMB interest.  I now see there is some description in the Training Guide manual – so perhaps some of my questions answered there.

Incidentally, there is some descriptive paragraph already there that describes the OECD Frascati Manual revision as “forthcoming.”   It was published in October of last year (2015).  So that statement needs to be revised.  But wasn’t obvious if I could directly edit that text.


Mark Boroush
Senior Analyst
National Science Foundation, National Center for Science and Engineering Statistics
4201 Wilson Boulevard, Room 965.47
Arlington, Virginia 22230
phone: 703.292.8726
email: mboroush@nsf.gov

National Center for Science and Engineering Statistics
www.nsf.gov/statistics/<http://www.nsf.gov/statistics/>

**Comment by JenPark9** [comment]
Thanks, Mark. I see that Francisco has also sent you a note that might be helpful in determining which metadata to provide. Re the Frascati Manual revision, I think that is something that we will update after confirming with our colleagues at UNSD as a courtesy—they are the source for the global metadata provided for the indicators at the moment. (Francisco, can you follow up with Abdullah or Matthias on that?)

**Comment by mboroush** [comment]
OK.  Francisco and I will converse.  Whatever issues there may be will no doubt be straightforwardly resolved!

Fine on the UNSD input.  I do appreciate the need for diplomacy here.


Mark Boroush
Senior Analyst
National Science Foundation, National Center for Science and Engineering Statistics
4201 Wilson Boulevard, Room 965.47
Arlington, Virginia 22230
phone: 703.292.8726
email: mboroush@nsf.gov

National Center for Science and Engineering Statistics
www.nsf.gov/statistics/<http://www.nsf.gov/statistics/>

**Comment by JenPark9** [comment]
You are very kind, Mark. Thank you!

**Comment by mboroush** [comment]
Jen:

I just entered the metadata info.  Pretty much following Francisco’s guidance in the training guide.

There are several ways I might have responded to some of the data requests.  Let me know if this is what you wanted.  I’d be happy to revise as directed.


Mark Boroush
Senior Analyst
National Science Foundation, National Center for Science and Engineering Statistics
4201 Wilson Boulevard, Room 965.47
Arlington, Virginia 22230
phone: 703.292.8726
email: mboroush@nsf.gov

National Center for Science and Engineering Statistics
www.nsf.gov/statistics/<http://www.nsf.gov/statistics/>

**Comment by JenPark9** [comment]
Much appreciated, Mark. In touch soon.

**Pull request merged**
