### PR TITLE
Updated indicator_17-6-2.csv

### PR DESCRIPTION
**Pull request by DonnaChristianson**
This pull request has been automatically generated by prose.io.

### CODE REVIEW

**Comment by JenPark9** [comment]
Thank you. Please confirm this is a real submission.

**Comment by DonnaChristianson** [comment]
This submission is not a real submission.  It was part of today’s training session.

**Comment by JenPark9** [comment]
Thank you. Please go back in and delete your entries and I will refresh.

Sent from my iPhone

On Nov 15, 2016, at 1:59 PM, DonnaChristianson <notifications@github.com<mailto:notifications@github.com>> wrote:

This submission is not a real submission. It was part of today's training session.

**Comment by DonnaChristianson** [comment]
I went in and changed the data back to zero.

**Pull request merged**
