### PR TITLE
Updated 4-c-1.md

### PR DESCRIPTION
**Pull request by Snyder1789**
This pull request has been automatically generated by prose.io.

### CODE REVIEW

**Comment by JenPark9** [comment]
Tom, there may have been a snarl with this update. Can I ask you to check 4-c-1.md and confirm that all updates have been made/are reflected? Thank you! Jen

**Comment by Snyder1789** [comment]
Hi Jen (pretty sure that I can’t reply directly to your comments).,
It looks sort of okay. I am not really certain what level of meta data is required. We only have data for 2007-08 and 2011-12.

I got an email after this one indicating it is closed? I clicked save several times while I was working and it may have generated some incomplete versions.

I thought we only had these two indicators due in September, and that the rest were due in October.  I am not going to be able to do a lot more on this project (other than fix what I have submitted), until I get back from Paris next week. I am leaving this afternoon, and I am trying to fix a bunch of stuff.

Thanks
Tom

**Comment by JenPark9** [comment]
Hi Tom,
Don’t worry about the “closed” email. ☺
For the metadata, I will need you to fill in the first two rows under national metadata—the actual indicator available and its description. Then, I will need you to fill in the date of the national public data release. Then, you will be all done with it.
It’s ok about the other indicators. I understand completely. Be safe!
Best, Jen

**Comment by Snyder1789** [comment]
Hi Jen,
I think I filled in the blocks. Let me know if this didn’t work and I will try again.
Thanks
Tom

**Comment by Snyder1789** [comment]
Tom,
I am so sorry, but I am not seeing your updates. Can I ask you to try one more time? So sorry.
Best, Jen

From: Snyder, Tom [mailto:Tom.Snyder@ed.gov]
Sent: Monday, October 3, 2016 10:44 AM
To: 'GSA/sdg-indicators' <reply@reply.github.com>; GSA/sdg-indicators <sdg-indicators@noreply.github.com>; Park, Jennifer E. EOP/OMB <Jennifer_E_Park@omb.eop.gov>
Cc: Author <author@noreply.github.com>
Subject: RE: [GSA/sdg-indicators] Updated 4-c-1.md (#152)

Hi Jen,
I think I filled in the blocks. Let me know if this didn’t work and I will try again.
Thanks
Tom

**Comment by Snyder1789** [comment]
Hi Jen,
Tried again. Did that work?
Thanks
Tom


From: Park, Jennifer E. EOP/OMB [mailto:Jennifer_E_Park@omb.eop.gov]
Sent: Monday, October 3, 2016 11:15 AM
To: Snyder, Tom; 'GSA/sdg-indicators'; GSA/sdg-indicators
Cc: Author
Subject: RE: [GSA/sdg-indicators] Updated 4-c-1.md (#152)

Tom,
I am so sorry, but I am not seeing your updates. Can I ask you to try one more time? So sorry.
Best, Jen

From: Snyder, Tom [mailto:Tom.Snyder@ed.gov]
Sent: Monday, October 3, 2016 10:44 AM
To: 'GSA/sdg-indicators' <reply@reply.github.com>; GSA/sdg-indicators <sdg-indicators@noreply.github.com<mailto:sdg-indicators@noreply.github.com>>; Park, Jennifer E. EOP/OMB <Jennifer_E_Park@omb.eop.gov<mailto:Jennifer_E_Park@omb.eop.gov>>
Cc: Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Subject: RE: [GSA/sdg-indicators] Updated 4-c-1.md (#152)

Hi Jen,
I think I filled in the blocks. Let me know if this didn’t work and I will try again.
Thanks
Tom

**Comment by Snyder1789** [comment]
Beautiful! Thank you, Tom!

From: Snyder, Tom [mailto:Tom.Snyder@ed.gov]
Sent: Monday, October 3, 2016 11:25 AM
To: Park, Jennifer E. EOP/OMB <Jennifer_E_Park@omb.eop.gov>; 'GSA/sdg-indicators' <reply@reply.github.com>; GSA/sdg-indicators <sdg-indicators@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [GSA/sdg-indicators] Updated 4-c-1.md (#152)

Hi Jen,
Tried again. Did that work?
Thanks
Tom


From: Park, Jennifer E. EOP/OMB [mailto:Jennifer_E_Park@omb.eop.gov]
Sent: Monday, October 3, 2016 11:15 AM
To: Snyder, Tom; 'GSA/sdg-indicators'; GSA/sdg-indicators
Cc: Author
Subject: RE: [GSA/sdg-indicators] Updated 4-c-1.md (#152)

Tom,
I am so sorry, but I am not seeing your updates. Can I ask you to try one more time? So sorry.
Best, Jen

From: Snyder, Tom [mailto:Tom.Snyder@ed.gov]
Sent: Monday, October 3, 2016 10:44 AM
To: 'GSA/sdg-indicators' <reply@reply.github.com>; GSA/sdg-indicators <sdg-indicators@noreply.github.com<mailto:sdg-indicators@noreply.github.com>>; Park, Jennifer E. EOP/OMB <Jennifer_E_Park@omb.eop.gov<mailto:Jennifer_E_Park@omb.eop.gov>>
Cc: Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Subject: RE: [GSA/sdg-indicators] Updated 4-c-1.md (#152)

Hi Jen,
I think I filled in the blocks. Let me know if this didn’t work and I will try again.
Thanks
Tom

**Pull request closed without merging**
