### PR TITLE
Updated 8-5-2.md

### PR DESCRIPTION
**Pull request by mwdumas**
This pull request has been automatically generated by prose.io.

### CODE REVIEW

**Comment by JenPark9** [comment]
Thank you, Mark. I am accepting this pull request now. Please take a look to make sure that everything appears as intended. Best, Jennifer

**Comment by mwdumas** [comment]
Jennifer - The data are not displayed by persons with disability vs. persons without disability.  Rather, included in the section entitled "persons with disabilities" are two rows of data per year.  The first row shows rates for persons with disabilities.  The second row of data for the same year represents persons without disabilities.  There are no entries in the "persons without disabilities" section.  Do I need to further label the columns with information about disabilities vs. no disabilities (the column titles are getting unwieldy) to correct this?

**Comment by JenPark9** [comment]
Hi Mark,
Wait one moment and I will help you out.
Best, Jen

**Comment by mwdumas** [comment]
Thanks Jennifer.  I also note that the text for the section of the metadata tab entitled "Description of the Actual Indicator Available" is missing and I can't seem to get the text to save.  Mark

**Comment by JenPark9** [comment]
I am working on making this a flat file. I will ask you to check the data in a moment.
If you can send me the metadata for the “description” cell, I will insert it for you.

**Comment by mwdumas** [comment]
Apologies - I didn't intend to "make" more work for you.  I would have been happy to update the file.

Here is the language I am trying to add to the "Description of the Actual Indicator Available" section of the metadata tab (not sure why it won't save), 

""The unemployment rate represents the number of unemployed persons as a percent of the civilian labor force. Unemployed persons are those who had no employment during the reference week, were available for work at that time, and had made specific efforts to find employment sometime during the 4-week period ending with the reference week. Persons who were waiting to be recalled to a job from which they had been laid off need not have been looking for work to be classified as unemployed. The civilian labor force comprises all persons classified as employed or unemployed.

The CPS uses a set of six questions to identify persons with disabilities. In the CPS, persons are classified as having a disability if there is a response of ""yes"" to any of these questions:
1. Is anyone deaf or does anyone have serious difficulty hearing? 
2. Is anyone blind or does anyone have serious difficulty seeing even when wearing glasses?
3. Because of a physical, mental, or emotional condition, does anyone have serious difficulty concentrating, remembering, or making decisions?
4. Does anyone have serious difficulty walking or climbing stairs?
5. Does anyone have difficulty dressing or bathing?
6. Because of a physical, mental, or emotional condition, does anyone have difficulty doing errands alone such as visiting a doctor's office or shopping?"

Thanks,

Mark

**Comment by JenPark9** [comment]
My pleasure, Mark. It was probably easier for me to adjust the data table. Please take a look at the page for data and metadata in about 10 minutes, after it has refreshed and make sure it looks ok. (It probably didn’t let you save earlier because I was working in the file.)
Thank you, Jen

**Comment by mwdumas** [comment]
Jennifer - I will review the data and if there are any issues I will be in touch with you tomorrow.  I also have data for 8.5.1, which I believe is our only outstanding Indicator at this point, that I want to discuss with you before entering it into the NRP.  Will I be able to reach you at the office tomorrow?

Thanks,

Mark

**Pull request merged**
