### PR TITLE
Updated indicator_6-5-1.csv

### PR DESCRIPTION
**Pull request by nicolenorris**
This pull request has been automatically generated by prose.io.

### CODE REVIEW

**Comment by JenPark9** [comment]
Hi Nicole,
Please let me know if you have completed entering your information for this indicator.
Thank you, Jennifer

**Comment by nicolenorris** [comment]
Hello Jen,

I have not yet entered any data for this indicator. I plan to do so this week.

Nicole Norris
Agricultural Statistician
International Programs Office
USDA, National Agricultural Statistics Service
Office Phone:  (202) 720-6016
Cell Phone: (202) 619-9279

**Comment by JenPark9** [comment]
Thank you, Nicole.

**Comment by JenPark9** [comment]
HI Nicole,
Thank you for your inputs. Because you have submitted several "pull" requests, the requests may become "snarled" in the thread. Therefore, I am "accepting" your inputs now. You may continue to edit and add content to the data and metadata pages as usual according to the training guide instructions. 
Thank you, Jennifer

**Pull request merged**
