### PR TITLE
Data update 12_21_16

### PR DESCRIPTION
**Pull request by andrew-craig-bea**
This pull request has been automatically generated by prose.io.

### CODE REVIEW

**Comment by JenPark9** [comment]
Hi Andrew,
Thank you for this, and for 17.3.2. Do you have prior years available as well? We try to go back as far as 2007. You would just insert a row in the table for prior years. Please let us know.
Thank you, Jennifer

**Comment by andrew-craig-bea** [comment]
Yes I do have data for 2007. I wasn’t sure since 2015 was the only year listed. I’ll go back and add them

**Comment by JenPark9** [comment]
Ok, cool. So, for every year you have them beginning in 2007 (through 2015).

**Comment by andrew-craig-bea** [comment]
Yes

**Pull request merged**
