### PR TITLE
Update 5-b-1.md

### PR DESCRIPTION
**Pull request by lewis410**
This pull request has been automatically generated by prose.io.

### CODE REVIEW

**Comment by JenPark9** [comment]
Thanks, Jamie! Please confirm that you have no further updates to this indicator by return email.

**Comment by lewis410** [comment]
The updates I provide for indicator 5.b.1 are all I have. There is no additional data going back to 2000 (the indicator didn't appear before 2011) or to 2016 (the next CPS Computer and Internet Use Supplement is scheduled for 11/17). In the metadata, I updated the Date of public data release from national source, Date of last update of this page, Staff email, and Indicator web address.


Thanks,

Jamie


Jamie Lewis, Ph.D.

Statistician, Education and Social Stratification Branch

U.S. Census Bureau

(301) 763-4535

jamie.lewis-owen@census.gov<mailto:jamie.michelle.lewis@census.gov>

________________________________

**Comment by JenPark9** [comment]
Thanks, Jamie. I’ve made a note re data availability. Much appreciated!

**Comment by lewis410** [comment]
Thanks for the update, Jamie.


Amy

________________________________

**Pull request merged**
