### PR TITLE
Updated indicator_9-1-2.csv

### PR DESCRIPTION
**Pull request by sbeningo**
This pull request has been automatically generated by prose.io.

### CODE REVIEW

**Comment by JenPark9** [comment]
HI Steve,
Thank you for this. To confirm, you do not have statistics for the first three columns under 2015?
Thank you, Jennifer

**Comment by sbeningo** [comment]
Yes – that is correct.

**Comment by JenPark9** [comment]
Thanks, Steve. Just let me know when you have notified the expert group co-chairs. An example email is below.

CC:  Jennifer Park; Rolf Schmidt

Dear
Dan Balzer (BalzerDK@state.gov<mailto:BalzerDK@state.gov>);
Wilson Sumner (SumnerW@state.gov<mailto:SumnerW@state.gov>)

I wanted to let you know that the statistics and metadata for indicator 9.1.2 has been populated on the national reporting platform. You can view the site at: https://gsa.github.io/sdg-indicators/.
If you have any questions, please let me know.
Sincerely,

**Comment by sbeningo** [comment]
Jennifer,
     I have no idea who the expert group co-chairs are.  Please let me know.
          Steve

**Comment by JenPark9** [comment]
Hi Steve,
They are highlighted below.
Thanks!
Jennifer

**Comment by sbeningo** [comment]
Jennifer,
    Nothing is highlighted in the below e-mail.  Who do I send the e-mail to?  Do I send it to Dan Balzer and Wilson Summer and CC: you and Rolf Schmidt?
           Steve

**Comment by JenPark9** [comment]
Yes—you may not be able to see the highlight because my email may arrive to you in plain text rather than rich text. But those are the right folks to email. Thank  you!

**Pull request merged**
