### PR TITLE
Updated indicator_4-a-1.csv

### PR DESCRIPTION
**Pull request by Snyder1789**
This pull request has been automatically generated by prose.io.

### CODE REVIEW

**Comment by JenPark9** [comment]
You're t he best!

**Comment by Snyder1789** [comment]
Did you get the meta data?

**Comment by JenPark9** [comment]
No, not for 4.a.1. Also, the varnames for the columns need to be in the format used in 3.2.1. –like a single varname instead of a data label.
Sorry!

**Comment by Snyder1789** [comment]
Hi Jen,
Hold on. I didn’t understand the assignment.  For the data sheets, we are only to provide a var name in the label field?  Then, someplace on the meta data we are to supply a translation of the variable names and the labels?

This is important for me to understand, because I need to resubmit everything.

Thanks
Tom

**Comment by JenPark9** [comment]
Yes, but I can fix them for you among the ones you've already submitted. Because I like you. ??? I will do tomorrow.

Sent from my iPhone

On Oct 25, 2016, at 5:56 PM, Snyder1789 <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Jen,
Hold on. I didn't understand the assignment. For the data sheets, we are only to provide a var name in the label field? Then, someplace on the meta data we are to supply a translation of the variable names and the labels?

This is important for me to understand, because I need to resubmit everything.

Thanks
Tom

**Comment by Snyder1789** [comment]
Hi Jen,
This is not that easy to fix. I don’t mind making repairs, but I need to understand what is the naming convention. Also, I would think that in theory I should carry the naming convention over to the parity index indicator, because it is asking for much of the same data that I have already entered in other indicators. Shouldn’t we be using the same variable names for that as we use for the other indicators?  Or, does each indicator have its own set of var names (all using the same var names in fact).

If the variables are just called var_a , etc. through each indicator, then there is some program that is going to tag each of the variable names with the indicator names so everything is unique?  Then, which block in the Meta data, do we put the cross walk of the var names with the actual labels.

Thanks
Tom

**Comment by JenPark9** [comment]
Francisco,
Can I ask  you to help Tom with this? GSA will make the crosswalk for us, but Tom is asking where to put the variable labels in the metadata table. Tom, Francisco will edit your variable labels for you into varnames.
Thank you, Jennifer

**Comment by Snyder1789** [comment]
Hi Jen,
I am trying to be good even if I am really bad.  Just let me know what is supposed to be done and I will take a stab at trying to fix things.
Thanks
Tom

**Comment by Snyder1789** [comment]
Hi Jen,
Francisco and I got this worked out yesterday. All my revised submissions should have valid variable names and the crosswalks have been pasted into the metadata in the block that we agreed upon.

I think I have things straight and you have already approved most of the indicators I revised last night.  I think I only have 3 regular indicators and the parity indicator to complete.  One other indicator has lost metadata and I need to recreate that.

Thanks
Tom

**Pull request merged**
